defmodule Mmentum.Repo.Migrations.CreateAttestoPhoenixTables do
  @moduledoc false

  # Generated by `mix attesto_phoenix.gen.migration`.
  #
  # Backing tables for the Ecto-based attesto_phoenix stores. See the task
  # moduledoc for the RFC each table implements.

  use Ecto.Migration

  def up do
    prefix = nil

    # A non-default runtime prefix is a PostgreSQL schema, not a table-name
    # fragment. Create it if needed, but leave it in place on rollback: it
    # may be shared by other application tables or migrations.

    # Authorization code grant store (RFC 6749, section 4.1), backing
    # AttestoPhoenix.Schema.Authorization / AttestoPhoenix.Store.EctoCodeStore.
    # One row per issued code. Only the hash of the code is stored (RFC 6749,
    # section 10.3); it is the PRIMARY KEY and the single-use lookup key
    # (EctoCodeStore.take/1 claims it with a conditional UPDATE by code_hash).
    # The schema keys on :code_hash, so there is no surrogate id. A primary
    # key, not merely a unique index, also supplies the usable index selected
    # by REPLICA IDENTITY DEFAULT. A logical-replication publication needs
    # that identity when it includes this table's UPDATE or DELETE operations.
    create table(:attesto_authorization_codes, primary_key: false, prefix: prefix) do
      add :code_hash, :string, size: 88, primary_key: true, null: false
      add :client_id, :string, size: 255, null: false
      add :subject, :string, size: 255, null: false
      add :scope, {:array, :string}, null: false, default: []
      # RFC 8707 resource indicator(s) bound at authorization time; the token
      # endpoint mints the access token `aud` from this set.
      add :resource, {:array, :string}, null: false, default: []
      add :redirect_uri, :text, null: false
      # PKCE binding (RFC 7636, section 4.3). Stored so the token endpoint can
      # verify the code_verifier presented at redemption.
      add :code_challenge, :string, size: 255
      add :code_challenge_method, :string, size: 16
      # RFC 7800 confirmation (DPoP key thumbprint, RFC 9449 section 6, or mTLS
      # thumbprint, RFC 8705 section 3.1). NULL for an unbound code.
      add :cnf, :map
      # OIDC request nonce (OpenID Connect Core, section 3.1.2.1).
      add :nonce, :string, size: 255
      # Opaque request claims round-tripped to redemption.
      add :claims, :map, null: false, default: %{}
      # Grant family linking this authorization code to descendants that must
      # be revoked if the code is replayed.
      add :family_id, :string, size: 255
      # The access token minted by a successful redemption; used only for
      # revocation after authorization-code reuse.
      add :access_token_jti, :string, size: 255
      add :access_token_expires_at, :utc_datetime
      add :access_token_revoked_at, :utc_datetime
      add :expires_at, :utc_datetime, null: false
      # consumed_at is set by the atomic claim. consumed_success is set only
      # after redemption validation passes, letting later re-presentation revoke
      # descendants while a failed first presentation remains plain invalid_grant.
      add :consumed_at, :utc_datetime
      add :consumed_success, :boolean, null: false, default: false
      # The schema carries an explicit :inserted_at (no :updated_at).
      add :inserted_at, :utc_datetime, null: false
    end

    # A duplicate code hash violates attesto_authorization_codes_pkey, the
    # primary-key name the schema maps onto the changeset alongside the legacy
    # unique-index name for rolling upgrades. Single-use redemption is
    # enforced by take/1's conditional UPDATE of consumed_at.
    # Expiry sweeps scan by expiry (AttestoPhoenix.Store.Sweeper).
    create index(:attesto_authorization_codes, [:expires_at], prefix: prefix)
    create index(:attesto_authorization_codes, [:family_id], prefix: prefix)
    create index(:attesto_authorization_codes, [:access_token_jti], prefix: prefix)

    # Refresh token store (RFC 6749, section 6), backing
    # AttestoPhoenix.Schema.RefreshToken / AttestoPhoenix.Store.EctoRefreshStore.
    # Rotation with reuse detection (RFC 6819, section 5.2.2.3): every rotation
    # issues a new row in the same family; presenting a consumed token revokes
    # the family. consumed/family_revoked are the booleans the atomic claim and
    # sticky revocation flip.
    create table(:attesto_refresh_tokens, primary_key: false, prefix: prefix) do
      add :id, :binary_id, primary_key: true
      add :token_hash, :string, size: 88, null: false
      add :family_id, :string, size: 255, null: false
      add :generation, :integer, null: false, default: 0
      add :client_id, :string, size: 255
      add :subject, :string, size: 255, null: false
      add :scope, {:array, :string}, null: false, default: []
      # RFC 8707 resource indicator(s) bound to the grant; carried through
      # rotation (subset-only narrowing) so the refreshed token's `aud` matches.
      add :resource, {:array, :string}, null: false, default: []
      # RFC 9470 / OIDC Core: original authentication context, carried across
      # rotation so a refreshed access token reports the real auth event
      # (auth_time is never re-stamped). auth_time is unix seconds.
      add :acr, :string
      add :auth_time, :bigint
      add :cnf, :map
      add :claims, :map, null: false, default: %{}
      # consumed is flipped false -> true by the atomic rotation claim
      # (UPDATE ... WHERE consumed = false); a missed update with the row still
      # present is the reuse signal.
      add :consumed, :boolean, null: false, default: false
      # consumed_at and successor support a short idempotency window for an
      # honest retry whose successful rotation response was lost.
      add :consumed_at, :utc_datetime
      add :successor, :map
      # family_revoked is sticky: a revoked family refuses every later insert.
      add :family_revoked, :boolean, null: false, default: false
      add :expires_at, :utc_datetime, null: false
      # Diagnostic lineage: the predecessor's token_hash, or NULL for the first
      # token in a family. Never a lookup key.
      add :parent_hash, :string, size: 88

      # The schema declares timestamps(updated_at: false): an :inserted_at, no
      # :updated_at.
      timestamps(updated_at: false, type: :utc_datetime)
    end

    # Token presentation looks up by hash; it must be unique to keep lookup and
    # rotation atomic. The default index name attesto_refresh_tokens_token_hash_index
    # matches the schema's unique_constraint(:token_hash, name: ...).
    create unique_index(:attesto_refresh_tokens, [:token_hash], prefix: prefix)
    # One generation per family prevents a concurrent or corrupted rotation
    # from creating two sibling successors.
    # Keep this name aligned with Schema.RefreshToken's unique_constraint/3.
    create unique_index(
             :attesto_refresh_tokens,
             [:family_id, :generation],
             name: :attesto_refresh_tokens_family_id_generation_index,
             prefix: prefix
           )

    # Family-wide revocation scans by family_id.
    create index(:attesto_refresh_tokens, [:family_id], prefix: prefix)
    create index(:attesto_refresh_tokens, [:expires_at], prefix: prefix)

    # Durable family revocation tombstones. This table is deliberately
    # separate from refresh-token rows because the sweeper may delete every
    # expired row in a family. The primary key makes revoke idempotent and
    # keeps marker lookups/insert checks cheap.
    create table(:attesto_refresh_family_revocations, primary_key: false, prefix: prefix) do
      add :family_id, :string, size: 255, primary_key: true, null: false
      add :revoked_at, :utc_datetime, null: false
    end

    # Device authorization grant (RFC 8628), backing
    # AttestoPhoenix.Schema.DeviceCode / AttestoPhoenix.Store.EctoDeviceCodeStore.
    # A device code is a mutable row moving pending -> approved|denied ->
    # consumed; each transition is one guarded atomic UPDATE in the store. Only
    # the device_code hash is stored; user_code is the normalized verification
    # key. last_polled_at enforces the section 3.5 minimum poll interval.
    create table(:attesto_device_codes, primary_key: false, prefix: prefix) do
      add :id, :binary_id, primary_key: true
      add :device_code_hash, :string, size: 88, null: false
      add :user_code, :string, size: 255, null: false
      add :client_id, :string, size: 255, null: false
      add :scope, {:array, :string}, null: false, default: []
      # RFC 8707 resource indicator(s) bound at the device-authorization endpoint.
      add :resource, {:array, :string}, null: false, default: []
      # RFC 9449 section 10 DPoP holder-of-key pre-binding (NULL for unbound).
      add :dpop_jkt, :string, size: 255
      # pending | approved | denied | consumed (the state machine).
      add :status, :string, size: 16, null: false, default: "pending"
      # Bound at approval (NULL until the user authorizes).
      add :subject, :string, size: 255
      add :granted_scope, {:array, :string}
      add :granted_claims, :map
      # Unix-second-truncated timestamp of the last accepted poll (NULL before
      # the first); the atomic slow_down guard compares against it.
      add :last_polled_at, :utc_datetime
      add :expires_at, :utc_datetime, null: false

      timestamps(updated_at: false, type: :utc_datetime)
    end

    # The device polls by device_code_hash and the verification page resolves by
    # user_code; both are unique single-use lookup keys.
    create unique_index(:attesto_device_codes, [:device_code_hash], prefix: prefix)
    create unique_index(:attesto_device_codes, [:user_code], prefix: prefix)
    create index(:attesto_device_codes, [:expires_at], prefix: prefix)

    # OpenID Connect CIBA authentication requests (CIBA Core 1.0), backing
    # AttestoPhoenix.Schema.CIBARequest / AttestoPhoenix.Store.EctoCIBAStore. A
    # CIBA request is a mutable row moving pending -> approved|denied ->
    # consumed; each transition is one guarded atomic UPDATE in the store. Only
    # the auth_req_id hash is stored. The §7.3 poll interval is frozen into the
    # `interval` column at issue (it is the value the client was told).
    create table(:attesto_ciba_requests, primary_key: false, prefix: prefix) do
      add :id, :binary_id, primary_key: true
      add :auth_req_id_hash, :string, size: 88, null: false
      add :client_id, :string, size: 255, null: false
      # poll | ping | push (FAPI-CIBA forbids push).
      add :delivery_mode, :string, size: 16, null: false
      add :scope, {:array, :string}, null: false, default: []
      add :acr_values, {:array, :string}, null: false, default: []
      add :binding_message, :string
      # Ping/push only: the client-generated bearer secret the notification POST
      # carries (NULL for poll). A single-flow-scoped, short-lived secret.
      # `:text`, not `:string(255)`: CIBA Core §7.3 sets no length bound and a
      # client may present a long high-entropy token (the conformance client does).
      add :client_notification_token, :text
      # The hint-resolved end-user the OP set out to authenticate (CIBA §7.1:
      # identified BEFORE the auth_req_id is issued). Bound at issue.
      add :hint_subject, :string, size: 255, null: false
      # RFC 8707 resource indicator(s) bound at the backchannel endpoint.
      add :resource, {:array, :string}, null: false, default: []
      # RFC 9449 §10 DPoP holder-of-key pre-binding (NULL for unbound).
      add :dpop_jkt, :string, size: 255
      # pending | approved | denied | consumed (the state machine).
      add :status, :string, size: 16, null: false, default: "pending"
      # Bound at approval (NULL until the user authenticates).
      add :subject, :string, size: 255
      add :acr, :string
      add :auth_time, :utc_datetime
      add :granted_scope, {:array, :string}
      add :granted_claims, :map
      # The §7.3 minimum seconds between accepted polls, frozen at issue.
      add :interval, :integer, null: false, default: 0
      add :last_polled_at, :utc_datetime
      add :expires_at, :utc_datetime, null: false

      timestamps(updated_at: false, type: :utc_datetime)
    end

    # The token endpoint redeems by auth_req_id_hash (the single-use poll key).
    create unique_index(:attesto_ciba_requests, [:auth_req_id_hash], prefix: prefix)
    create index(:attesto_ciba_requests, [:expires_at], prefix: prefix)

    # Logout session store (OpenID Connect Back-Channel Logout 1.0 +
    # Front-Channel Logout 1.0), backing AttestoPhoenix.Schema.LogoutSession /
    # AttestoPhoenix.Store.EctoLogoutSessionStore. One row per (session, RP)
    # pair, recorded at ID-Token mint and enumerated at the end-session
    # endpoint to deliver a logout_token (back-channel) and/or render the RP's
    # frontchannel_logout_uri in an iframe (front-channel); at least one of the
    # two URIs is present. Upserted on (sid, client_id); read by sid
    # (session-scoped logout) or subject (all the subject's sessions).
    create table(:attesto_logout_sessions, primary_key: false, prefix: prefix) do
      add :id, :binary_id, primary_key: true
      add :sid, :string, size: 255, null: false
      add :subject, :string, size: 255, null: false
      add :client_id, :string, size: 255, null: false
      add :backchannel_logout_uri, :text
      # The RP's backchannel_logout_session_required: whether its logout token
      # MUST carry sid (Back-Channel Logout 1.0 section 2.2).
      add :session_required, :boolean, null: false, default: false
      add :frontchannel_logout_uri, :text
      # The RP's frontchannel_logout_session_required: whether the rendered
      # logout URI must carry iss/sid (Front-Channel Logout 1.0 section 2).
      add :frontchannel_session_required, :boolean, null: false, default: false
      add :expires_at, :utc_datetime, null: false

      timestamps(updated_at: false, type: :utc_datetime)
    end

    # Upsert key: re-issuing an ID Token for a session the RP already holds
    # refreshes the row rather than duplicating it. The default index name
    # attesto_logout_sessions_sid_client_id_index matches the schema's
    # unique_constraint([:sid, :client_id], name: ...).
    create unique_index(:attesto_logout_sessions, [:sid, :client_id], prefix: prefix)
    # Fan-out reads by sid or subject; sweeps scan by expires_at.
    create index(:attesto_logout_sessions, [:subject], prefix: prefix)
    create index(:attesto_logout_sessions, [:expires_at], prefix: prefix)

    # Server-issued DPoP nonces (RFC 9449, section 8), backing
    # AttestoPhoenix.Schema.DPoPNonce / AttestoPhoenix.Store.EctoNonceStore.
    # Each nonce is single-use: issued_at + the consume cutoff bound freshness,
    # and used_at (NULL while unused) is stamped exactly once.
    create table(:dpop_nonces, primary_key: false, prefix: prefix) do
      add :id, :binary_id, primary_key: true
      add :nonce, :string, size: 255, null: false
      add :issued_at, :utc_datetime, null: false
      add :expires_at, :utc_datetime, null: false
      add :used_at, :utc_datetime
    end

    # The default index name dpop_nonces_nonce_index matches the schema's
    # unique_constraint(:nonce) (which uses Ecto's default name).
    create unique_index(:dpop_nonces, [:nonce], prefix: prefix)
    # Partial index over still-unused rows keeps the conditional consume fast.
    create index(:dpop_nonces, [:used_at],
             where: "used_at IS NULL",
             name: :dpop_nonces_unused_index,
             prefix: prefix
           )

    # DPoP proof replay cache (RFC 9449, section 11.1), backing
    # AttestoPhoenix.Schema.DPoPReplay / AttestoPhoenix.Store.EctoReplayCheck.
    # The proof's jti (RFC 9449 section 4.2, RFC 7519 section 4.1.7) is the
    # PRIMARY KEY, so the atomic record-and-check is INSERT ... ON CONFLICT DO
    # NOTHING and the conflicting constraint is the primary key dpop_replays_pkey
    # the schema's unique_constraint(:jti, name: :dpop_replays_pkey) names.
    create table(:dpop_replays, primary_key: false, prefix: prefix) do
      add :jti, :string, size: 255, primary_key: true, null: false
      add :expires_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
    end

    # Expiry sweeps scan by expires_at; replay decisions hit the primary key.
    create index(:dpop_replays, [:expires_at], prefix: prefix)

    # Pushed Authorization Request store (RFC 9126), backing
    # AttestoPhoenix.Schema.PushedAuthorizationRequest /
    # AttestoPhoenix.Store.EctoPARStore. The one-time request_uri reference is
    # the PRIMARY KEY, so resolution at /authorize (and the optional single-use
    # take/1 = DELETE ... RETURNING) hits the primary key. The stored, validated
    # request params live in a jsonb column; expires_at bounds the reference's
    # life (RFC 9126 section 2.2) and is re-checked on read.
    create table(:attesto_pushed_authorization_requests, primary_key: false, prefix: prefix) do
      add :request_uri, :string, size: 255, primary_key: true, null: false
      add :params, :map, null: false
      add :expires_at, :utc_datetime, null: false
      add :inserted_at, :utc_datetime, null: false
    end

    # Expiry sweeps scan by expires_at; resolution hits the primary key.
    create index(:attesto_pushed_authorization_requests, [:expires_at], prefix: prefix)

    # Client ID Metadata Document cache
    # (draft-ietf-oauth-client-id-metadata-document-01), backing
    # AttestoPhoenix.Schema.ClientIdMetadata /
    # AttestoPhoenix.ClientIdMetadata.Cache.Ecto. The CIMD client_id URL is the
    # PRIMARY KEY, so the cache lookup (get/1) hits the primary key and a
    # re-fetch upserts the single row. The validated document lives in a jsonb
    # metadata column; expires_at is the freshness derived from the response's
    # Cache-Control/Expires (RFC 9111), re-checked on read and indexed for
    # sweeps. Only validated documents are ever written here.
    create table(:attesto_client_id_metadata, primary_key: false, prefix: prefix) do
      add :url, :string, size: 255, primary_key: true, null: false
      add :metadata, :map, null: false
      add :expires_at, :utc_datetime, null: false
      add :inserted_at, :utc_datetime, null: false
    end

    # Expiry sweeps scan by expires_at; lookups hit the primary key.
    create index(:attesto_client_id_metadata, [:expires_at], prefix: prefix)

    # Single-use, request-bound consent grants (RFC 6749 section 4.1.1),
    # backing AttestoPhoenix.Schema.ConsentGrant /
    # AttestoPhoenix.Store.EctoConsentGrantStore. One row per consent decision,
    # keyed on an unguessable token (the PRIMARY KEY) so the conditional consume
    # UPDATE and the disambiguation read both hit the primary key. binding_hash
    # ties the grant to the exact request the user saw; consumed_at marks single
    # use; expires_at bounds the short consent window and is re-checked on
    # consume. The default index name attesto_consent_grants_pkey matches the
    # schema's unique_constraint(:token, name: :attesto_consent_grants_pkey).
    create table(:attesto_consent_grants, primary_key: false, prefix: prefix) do
      add :token, :string, size: 255, primary_key: true, null: false
      add :binding_hash, :string, size: 88, null: false
      add :subject, :string, size: 255, null: false
      add :consumed_at, :utc_datetime_usec
      add :expires_at, :utc_datetime_usec, null: false

      timestamps(type: :utc_datetime_usec)
    end

    # Expiry sweeps scan by expires_at; consume hits the primary key.
    create index(:attesto_consent_grants, [:expires_at], prefix: prefix)
  end

  def down do
    prefix = nil
    drop table(:attesto_consent_grants, prefix: prefix)
    drop table(:attesto_client_id_metadata, prefix: prefix)
    drop table(:attesto_pushed_authorization_requests, prefix: prefix)
    drop table(:dpop_replays, prefix: prefix)
    drop table(:dpop_nonces, prefix: prefix)
    drop table(:attesto_logout_sessions, prefix: prefix)
    drop table(:attesto_ciba_requests, prefix: prefix)
    drop table(:attesto_device_codes, prefix: prefix)
    drop table(:attesto_refresh_family_revocations, prefix: prefix)
    drop table(:attesto_refresh_tokens, prefix: prefix)
    drop table(:attesto_authorization_codes, prefix: prefix)
  end
end
